### ISSUE TITLE
How to change menu bar color, and add options

### ISSUE THREAD

**Issue by cars111** [abukwaik/Radix#3]
Hi guys first of all I would like to say that your starter theme is a breath of fresh air and works really well, as a designer I was looking for a responsive starter theme with most of the normal options you would find and I couldn't get a theme like that until now :)

Just a couple of questions. I cant find a way of changing the background color of the navbar. Also its it possible to add options?

I tried to install the redux plugin but your option page dissapears.

1 more thing can I use your theme to sell on themeforest?

Thanks again

**Comment by abukwaik** [comment]
Hi cars111,

Thanks, I'm so glad to hear that :blush:

Well, I checked and found that the option is there but it seems it doesn't work correctly. I've pushed a quick fix so please re-download the theme from GitHub source. Also, please note that you don't need to install "Redux" plugin since it is already embedded in the theme to avoid any conflict issues.

About selling on themeforest. Yes, you can since Radix starter theme is licensed under GPL v2 and 100% Open Source!

Regards.

**Comment by cars111** [comment]
Wow support is brilliant! I have  been searching for a starter theme like this for months i really have, ive downloaded loads of different ones. Why for the life of me dont they have the everyday options that everyone wants? Well you have come to the rescue thanks so much for the support :)

Sent from Samsung Mobile

-------- Original message --------

**Comment by abukwaik** [comment]
Thank you cars111, really appreciate your kind words. :relaxed:

**Comment by cars111** [comment]
hi how do I add a boxed layout grid? abd add it to options?  at the mo its full width and is causing a few issues with visual composer.  Thanks again
